name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 bandit mypy pip-audit black isort
    - name: Formatting with black
      if: always()
      continue-on-error: true
      run: |
        black $(git ls-files '*.py')
    - name: Analysing the code with pylint
      if: always()
      continue-on-error: true
      run: |
        pylint $(git ls-files '*.py')
    - name: Analysing the code with flake8
      if: always()
      continue-on-error: true
      run: |
        flake8 $(git ls-files '*.py')
    - name: Analysing the code with mypy
      if: always()
      continue-on-error: true
      run: |
        mypy $(git ls-files '*.py')
    - name: Alalysing the code with pip-audit
      if: always()
      continue-on-error: true
      run: |
        pip-audit $(git ls-files '*.py')
